### ISSUE TITLE
Data Export email link says "not authorized" even on admins

### ISSUE THREAD

**Issue by GraysonE** [ErhardLabs/tunefuze#229]

**Comment by erhardsc** [comment]
I'm not sure what the issue is with the data export link not working but that link is intended only for the admin email of the site.

When someone requests a data export the admin will be notified that someone is requesting it. From there the admin is supposed to go to see the request and then send the export link.

![Screen Shot 2020-03-04 at 12 35 39 PM](https://user-images.githubusercontent.com/17289312/75915962-b6f3a880-5e14-11ea-85f5-7d7d283971b7.png)

From there the user will receive their link to download which works on my end. The issue with the permissions to view the export link could be an issue with WordPress itself
