### ISSUE TITLE
Improve Lighthouse SEO Score - Edit Page

### ISSUE THREAD

**Issue by GraysonE** [ErhardLabs/tunefuze#388]
![Screen Shot 2020-05-27 at 7 14 19 PM](https://user-images.githubusercontent.com/7062755/83087335-4b555c00-a04e-11ea-9178-35ffe2761ee1.png)

**Comment by erhardsc** [comment]
@GraysonE 

I updated the image alt tags in this commit to Virtuoso
https://github.com/ErhardLabs/virtuoso/commit/10c2ea2bd8627a05a1522a12146c2e4a77dd6143

Added meta description tags to the edit pages based on the title of the fuze. Since I wrote a function that adds meta descriptions I went ahead and added a meta tag to the profile page as well.

![Screen Shot 2020-06-08 at 6 59 31 PM](https://user-images.githubusercontent.com/17289312/84094555-4da6a700-a9ba-11ea-92e6-d1e320d9dff9.png)

**Comment by GraysonE** [comment]
Awesome!
