### ISSUE TITLE
Body Opacity Still 0 on Some Pages

### ISSUE THREAD

**Issue by GraysonE** [ErhardLabs/tunefuze#72]
go to edit profile, save profile, the next screen will just be blue. We need to make sure the css class that makes the blue screen go away is on every single page.

**Comment by erhardsc** [comment]
@GraysonE 

When I add opacity: 1 to the body the page isn't even loaded all the way. There are no footer or header menu items, so this has to be something wrong with the save function itself.

I'll investigate this further and update you on what I find.

**Comment by erhardsc** [comment]
@GraysonE 

I've spent a while trying to get this to work and noticed a few things. I can confirm that this is not a front end issue and is indeed an issue with the save functionality specifically on the General tab.

All of the other tabs are saving and working as intended.

It seems like the issue are coming from what action the form is supposed to be posting to.
<img width="1405" alt="Screen Shot 2019-08-28 at 9 49 29 PM" src="https://user-images.githubusercontent.com/17289312/63908811-be597580-c9dd-11e9-9eb4-656a99656799.png">
The form is not able to build the proper URL to direct back to the site. But further digging into the template, I'm not sure that function is able to build that URL based off the current implementation.

Also, one of the things that I noticed was that all of the settings templates you are overriding are under the subpackage `bp-legacy`. If this is intentional then please let me know, but if not then please update all of the settings pages to the most current templates.

**Comment by GraysonE** [comment]
If the plugin Sexy Animations isn't activated, the body opacity won't get changed.
